variables:
  APT_PKGS: "zlib1g-dev libcairo2-dev libxt-dev libproj-dev libcurl4-openssl-dev libssl-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libxml2-dev"
  # RENV_CONFIG_REPOS_OVERRIDE: "http://cran.r-project.org"
  RENV_PATHS_CACHE: ${CI_PROJECT_DIR}/cache
  RENV_PATHS_LIBRARY: ${CI_PROJECT_DIR}/renv/library

cache:
  key: ${CI_JOB_NAME}
  paths:
    - ${RENV_PATHS_CACHE}
    - ${RENV_PATHS_LIBRARY}

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends ${APT_PKGS}
  # TODO: look into https://github.com/eddelbuettel/mkl4deb/issues/8
  # Utilize all cores for installing R packages.
  - echo "options(Ncpus = $(nproc --all))" >> /usr/local/lib/R/etc/Rprofile.site
  - Rscript -e "sessionInfo()"
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"

after_script:
  - Rscript -e "sessionInfo()"

run:
  image: rocker/r-ver:latest
  script:
      - Rscript differential-expression-analysis/dea.R --plots